SELECT * FROM CUSTOMERS;
SELECT * FROM VEHICLES;
SELECT * FROM "DIAGNOSTICS";
SELECT * FROM SERVICE;
SELECT * FROM STAFF;
SELECT * FROM BILLS;
SELECT * FROM GRADES;
SELECT * FROM MATERIALS;


DROP TABLE SERVICEDB.CUSTOMERS CASCADE CONSTRAINTS;
DROP TABLE SERVICEDB.VEHICLES CASCADE CONSTRAINTS;
DROP TABLE SERVICEDB."DIAGNOSTICS" CASCADE CONSTRAINTS;
DROP TABLE SERVICEDB.SERVICE CASCADE CONSTRAINTS;
DROP TABLE SERVICEDB.STAFF CASCADE CONSTRAINTS;
DROP TABLE SERVICEDB.BILLS CASCADE CONSTRAINTS;
DROP TABLE SERVICEDB.GRADES CASCADE CONSTRAINTS;
DROP TABLE SERVICEDB.MATERIALS CASCADE CONSTRAINTS;

--2 курсора. Вложенное курсорное выражение
ALTER TABLE STAFF ADD salary NUMBER(*,0);
UPDATE STAFF SET salary = 50000 WHERE ID_MASTER = 1;
UPDATE STAFF SET salary = 60000 WHERE ID_MASTER = 2;
UPDATE STAFF SET salary = 70000 WHERE ID_MASTER = 3;


--Реализовать пакет
ALTER TABLE STAFF
DROP COLUMN salary;

SELECT * FROM SERVICE;
INSERT INTO SERVICEDB.SERVICE VALUES (6, 'Замена фар освещения', 'Выполнено', 5, 1, 6, (select (SYSTIMESTAMP) from dual), 1, 3, 'Замена произведена');