#!/usr/bin/env python3
from PyQt5 import QtCore, QtGui, QtWidgets
from process import handle

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1112, 831)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setFocusPolicy(QtCore.Qt.WheelFocus)
        self.tabWidget.setAcceptDrops(True)
        self.tabWidget.setToolTipDuration(6)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.tab)
        self.scrollArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 1068, 750))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")

        self.groupBox_2 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_2.setGeometry(QtCore.QRect(660, 10, 401, 381))
        self.groupBox_2.setObjectName("groupBox_2")

        self.label_46 = QtWidgets.QLabel(self.groupBox_2)
        self.label_46.setGeometry(QtCore.QRect(70, 70, 21, 16))
        self.label_46.setObjectName("label_46")

        self.comboBox_2 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_2.setGeometry(QtCore.QRect(20, 70, 51, 20))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")

        self.comboBox_3 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_3.setGeometry(QtCore.QRect(20, 120, 51, 20))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")

        self.label_57 = QtWidgets.QLabel(self.groupBox_2)
        self.label_57.setGeometry(QtCore.QRect(70, 120, 21, 16))
        self.label_57.setObjectName("label_57")

        self.label_58 = QtWidgets.QLabel(self.groupBox_2)
        self.label_58.setGeometry(QtCore.QRect(70, 170, 21, 16))
        self.label_58.setObjectName("label_58")

        self.comboBox_4 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_4.setGeometry(QtCore.QRect(20, 170, 51, 20))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")

        self.comboBox_5 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_5.setGeometry(QtCore.QRect(20, 220, 51, 20))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")



        self.label_59 = QtWidgets.QLabel(self.groupBox_2)
        self.label_59.setGeometry(QtCore.QRect(70, 220, 21, 16))
        self.label_59.setObjectName("label_59")

        self.label_60 = QtWidgets.QLabel(self.groupBox_2)
        self.label_60.setGeometry(QtCore.QRect(70, 270, 21, 16))
        self.label_60.setObjectName("label_60")

        self.label_70 = QtWidgets.QLabel(self.groupBox_2)
        self.label_70.setGeometry(QtCore.QRect(70, 290, 21, 16))
        self.label_70.setObjectName("label_70")

        self.label_28 = QtWidgets.QLabel(self.groupBox_2)
        self.label_28.setGeometry(QtCore.QRect(11, 20, 16, 16))
        self.label_28.setObjectName("label_28")

        self.comboBox_1 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_1.setGeometry(QtCore.QRect(20, 20, 51, 20))
        self.comboBox_1.setObjectName("comboBox_1")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")
        self.comboBox_1.addItem("")

        self.expression_lineEdit_1_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_1_1.setGeometry(QtCore.QRect(100, 20, 42, 20))
        self.expression_lineEdit_1_1.setStyleSheet("min-width:40px;\n" "max-width:40px;\n" "width:40px")
        self.expression_lineEdit_1_1.setObjectName("expression_lineEdit_1_1")

        self.label_45 = QtWidgets.QLabel(self.groupBox_2)
        self.label_45.setGeometry(QtCore.QRect(70, 20, 21, 16))
        self.label_45.setObjectName("label_45")

        self.label_29 = QtWidgets.QLabel(self.groupBox_2)
        self.label_29.setGeometry(QtCore.QRect(150, 20, 41, 16))
        self.label_29.setObjectName("label_29")

        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(230, 20, 41, 16))
        self.label_32.setObjectName("label_32")
        
        self.label_44 = QtWidgets.QLabel(self.groupBox_2)
        self.label_44.setGeometry(QtCore.QRect(320, 20, 21, 16))
        self.label_44.setObjectName("label_44")

        self.expression_lineEdit_2_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_2_1.setGeometry(QtCore.QRect(100, 70, 42, 20))
        self.expression_lineEdit_2_1.setStyleSheet("min-width:40px;\n""max-width:40px;\n""width:40px")
        self.expression_lineEdit_2_1.setObjectName("expression_lineEdit_2_1")

        self.label_30 = QtWidgets.QLabel(self.groupBox_2)
        self.label_30.setGeometry(QtCore.QRect(11, 70, 16, 16))
        self.label_30.setObjectName("label_30")

        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        self.label_33.setGeometry(QtCore.QRect(160, 70, 20, 16))
        self.label_33.setObjectName("label_33")

        self.label_34 = QtWidgets.QLabel(self.groupBox_2)
        self.label_34.setGeometry(QtCore.QRect(11, 122, 16, 16))
        self.label_34.setObjectName("label_34")

        self.expression_lineEdit_3_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_3_1.setGeometry(QtCore.QRect(100, 120, 42, 20))
        self.expression_lineEdit_3_1.setStyleSheet("min-width:40px;\n""max-width:40px;\n""width:40px")
        self.expression_lineEdit_3_1.setObjectName("expression_lineEdit_3_1")

        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(150, 120, 34, 16))
        self.label_35.setObjectName("label_35")

        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setGeometry(QtCore.QRect(240, 120, 20, 16))
        self.label_36.setObjectName("label_36")

        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        self.label_37.setGeometry(QtCore.QRect(11, 171, 16, 16))
        self.label_37.setObjectName("label_37")

        self.expression_lineEdit_4_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_4_1.setGeometry(QtCore.QRect(100, 170, 42, 20))
        self.expression_lineEdit_4_1.setStyleSheet("min-width:40px;\n""max-width:40px;\n""width:40px")
        self.expression_lineEdit_4_1.setObjectName("expression_lineEdit_4_1")

        self.label_43 = QtWidgets.QLabel(self.groupBox_2)
        self.label_43.setGeometry(QtCore.QRect(160, 170, 20, 16))
        self.label_43.setObjectName("label_43")

        self.expression_lineEdit_5_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_5_1.setGeometry(QtCore.QRect(100, 220, 42, 20))
        self.expression_lineEdit_5_1.setStyleSheet("min-width:40px;\n""max-width:40px;\n""width:40px")
        self.expression_lineEdit_5_1.setObjectName("expression_lineEdit_5_1")

        self.label_39 = QtWidgets.QLabel(self.groupBox_2)
        self.label_39.setGeometry(QtCore.QRect(11, 221, 16, 16))
        self.label_39.setObjectName("label_39")

        self.label_40 = QtWidgets.QLabel(self.groupBox_2)
        self.label_40.setGeometry(QtCore.QRect(150, 220, 34, 16))
        self.label_40.setObjectName("label_40")

        self.label_41 = QtWidgets.QLabel(self.groupBox_2)
        self.label_41.setGeometry(QtCore.QRect(240, 220, 20, 16))
        self.label_41.setObjectName("label_41")

        self.label_61 = QtWidgets.QLabel(self.groupBox_2)
        self.label_61.setGeometry(QtCore.QRect(11, 290, 16, 16))
        self.label_61.setObjectName("label_61")

        self.comboBox_6 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_6.setGeometry(QtCore.QRect(20, 290, 51, 20))
        self.comboBox_6.setObjectName("comboBox_5")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")
        self.comboBox_6.addItem("")

        self.expression_lineEdit_6_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_6_1.setGeometry(QtCore.QRect(100, 290, 42, 20))
        self.expression_lineEdit_6_1.setStyleSheet("min-width:40px;\n""max-width:40px;\n""width:40px")
        self.expression_lineEdit_6_1.setObjectName("expression_lineEdit_6_1")
        
        self.label_71 = QtWidgets.QLabel(self.groupBox_2)
        self.label_71.setGeometry(QtCore.QRect(11, 270, 16, 16))
        self.label_71.setObjectName("label_71")

        self.comboBox_7 = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_7.setGeometry(QtCore.QRect(20, 270, 51, 20))
        self.comboBox_7.setObjectName("comboBox_5")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")
        self.comboBox_7.addItem("")

        self.expression_lineEdit_7_1 = QtWidgets.QLineEdit(self.groupBox_2)
        self.expression_lineEdit_7_1.setGeometry(QtCore.QRect(100, 270, 42, 20))
        self.expression_lineEdit_7_1.setStyleSheet("min-width:40px;\n""max-width:40px;\n""width:40px")
        self.expression_lineEdit_7_1.setObjectName("expression_lineEdit_7_1")



        self.groupBox_3 = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox_3.setGeometry(QtCore.QRect(660, 380, 401, 371))
        self.groupBox_3.setCheckable(False)
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_42 = QtWidgets.QLabel(self.groupBox_3)
        self.label_42.setGeometry(QtCore.QRect(90, 30, 49, 16))
        self.label_42.setObjectName("label_42")
        self.expression_lineEdit_41 = QtWidgets.QLineEdit(self.groupBox_3)
        self.expression_lineEdit_41.setGeometry(QtCore.QRect(150, 30, 113, 22))
        self.expression_lineEdit_41.setAlignment(QtCore.Qt.AlignCenter)
        self.expression_lineEdit_41.setObjectName("expression_lineEdit_41")
        self.pushButton = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton.setGeometry(QtCore.QRect(150, 70, 121, 31))
        self.pushButton.setObjectName("pushButton")
        
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_2.setGeometry(QtCore.QRect(150, 120, 121, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_3.setGeometry(QtCore.QRect(150, 170, 121, 31))
        self.pushButton_3.setObjectName("pushButton_3")
        self.groupBox = QtWidgets.QGroupBox(self.scrollAreaWidgetContents)
        self.groupBox.setGeometry(QtCore.QRect(9, 9, 651, 741))
        self.groupBox.setStyleSheet("max-width: 1000px")
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.groupBox)
        self.scrollArea_2.setMaximumSize(QtCore.QSize(1000, 600))
        self.scrollArea_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, -51, 612, 740))
        self.scrollAreaWidgetContents_2.setMaximumSize(QtCore.QSize(1000, 794))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout.setObjectName("gridLayout")
        self.label_13 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 13, 0, 1, 3)
       
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label.setStyleSheet("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)

        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)

        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)

        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)

        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)

        self.label_7 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 6, 0, 1, 1)
       
        self.label_8 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 7, 0, 1, 1)

        self.label_9 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 8, 0, 1, 1)

        self.label_10 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 9, 0, 1, 1)

        self.label_11 = QtWidgets.QLabel(self.scrollAreaWidgetContents_2)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 10, 0, 1, 1)

        self.begin_expression_lineEdit_11 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.begin_expression_lineEdit_11.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_11.setObjectName("begin_expression_lineEdit_11")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_11, 10, 7, 1, 1)
        self.begin_expression_lineEdit_10 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.begin_expression_lineEdit_10.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_10.setObjectName("begin_expression_lineEdit_10")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_10, 9, 7, 1, 1)
        self.begin_expression_lineEdit_9 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.begin_expression_lineEdit_9.setStyleSheet("min-width:50px; width: 50px")
        self.begin_expression_lineEdit_9.setObjectName("begin_expression_lineEdit_9")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_9, 8, 7, 1, 1)
        self.begin_expression_lineEdit_8 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.begin_expression_lineEdit_8.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_8.setObjectName("begin_expression_lineEdit_8")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_8, 7, 7, 1, 1)
        self.begin_expression_lineEdit_7 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.begin_expression_lineEdit_7.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_7.setObjectName("begin_expression_lineEdit_7")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_7, 6, 7, 1, 1)
        self.begin_expression_lineEdit_6 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.begin_expression_lineEdit_6.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_6.setObjectName("begin_expression_lineEdit_6")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_6, 5, 7, 1, 1)
        self.begin_expression_lineEdit_5 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.begin_expression_lineEdit_5.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_5.setObjectName("begin_expression_lineEdit_5")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_5, 4, 7, 1, 1)
        self.begin_expression_lineEdit_4 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.begin_expression_lineEdit_4.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_4.setObjectName("begin_expression_lineEdit_4")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_4, 3, 7, 1, 1)
        self.begin_expression_lineEdit_3 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.begin_expression_lineEdit_3.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_3.setObjectName("begin_expression_lineEdit_3")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_3, 2, 7, 1, 1)
        self.begin_expression_lineEdit_2 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.begin_expression_lineEdit_2.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_2.setObjectName("begin_expression_lineEdit_2")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_2, 1, 7, 1, 1)
        self.begin_expression_lineEdit_1 = QtWidgets.QLineEdit(self.scrollAreaWidgetContents_2)
        self.begin_expression_lineEdit_1.setStyleSheet("min-width:50px;\n"
"width:50px")
        self.begin_expression_lineEdit_1.setObjectName("begin_expression_lineEdit_1")
        self.gridLayout.addWidget(self.begin_expression_lineEdit_1, 0, 7, 1, 1)

        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.addWidget(self.scrollArea_2, 1, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 1, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setEnabled(True)
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_15 = QtWidgets.QLabel(self.tab_2)
        self.label_15.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_15.setStyleSheet("max-height : 800px;\n"
"max-width:1100px;\n"
"margin-top: 10px;\n"
"margin-bottom: 10px;")
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("../../.designer/Изображения/testImage.jpeg"))
        self.label_15.setScaledContents(True)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setIndent(-3)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setEnabled(True)
        self.tab_3.setObjectName("tab_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_3)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.scrollArea_3 = QtWidgets.QScrollArea(self.tab_3)
        self.scrollArea_3.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.scrollArea_3.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrollArea_3.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.scrollArea_3.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_3 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_3.setGeometry(QtCore.QRect(0, -1875, 1051, 2642))
        self.scrollAreaWidgetContents_3.setObjectName("scrollAreaWidgetContents_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_55 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_55.setStyleSheet("max-height : 800px;\n"
"max-width:900px;\n"
"margin-top: 10px;\n"
"margin-bottom: 10px;")
        self.label_55.setText("")
        self.label_55.setPixmap(QtGui.QPixmap("../Изображения/testImage.jpeg"))
        self.label_55.setScaledContents(True)
        self.label_55.setObjectName("label_55")
        self.gridLayout_5.addWidget(self.label_55, 3, 0, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_54.setMaximumSize(QtCore.QSize(700, 520))
        self.label_54.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_54.setStyleSheet("max-height : 800px;\n"
"max-width:900px;\n"
"margin-top: 10px;\n"
"margin-bottom: 10px;")
        self.label_54.setText("")
        self.label_54.setPixmap(QtGui.QPixmap("../Изображения/testImage.jpeg"))
        self.label_54.setScaledContents(True)
        self.label_54.setAlignment(QtCore.Qt.AlignCenter)
        self.label_54.setIndent(-3)
        self.label_54.setObjectName("label_54")
        self.gridLayout_5.addWidget(self.label_54, 1, 0, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_53.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_53.setStyleSheet("max-height : 800px;\n"
"max-width:900px;\n"
"margin-top: 10px;\n"
"margin-bottom: 10px;")
        self.label_53.setText("")
        self.label_53.setPixmap(QtGui.QPixmap("../Изображения/testImage.jpeg"))
        self.label_53.setScaledContents(True)
        self.label_53.setAlignment(QtCore.Qt.AlignCenter)
        self.label_53.setIndent(-3)
        self.label_53.setObjectName("label_53")
        self.gridLayout_5.addWidget(self.label_53, 0, 0, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_38.setMaximumSize(QtCore.QSize(700, 520))
        self.label_38.setText("")
        self.label_38.setPixmap(QtGui.QPixmap("../Изображения/testImage.jpeg"))
        self.label_38.setScaledContents(True)
        self.label_38.setObjectName("label_38")
        self.label_38.setStyleSheet("max-height : 800px;\n"
"max-width:900px;\n"
"margin-top: 10px;\n"
"margin-bottom: 10px;")
        self.gridLayout_5.addWidget(self.label_38, 2, 0, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.scrollAreaWidgetContents_3)
        self.label_62.setMaximumSize(QtCore.QSize(700, 520))
        self.label_62.setText("")
        self.label_62.setPixmap(QtGui.QPixmap("../Изображения/testImage.jpeg"))
        self.label_62.setScaledContents(True)
        self.label_62.setObjectName("label_62")
        self.label_62.setStyleSheet("max-height : 800px;\n"
"max-width:900px;\n"
"margin-top: 10px;\n"
"margin-bottom: 10px;")
        self.gridLayout_5.addWidget(self.label_62, 4, 0, 1, 1)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_3)
        self.verticalLayout_2.addWidget(self.scrollArea_3)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setEnabled(True)
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_56 = QtWidgets.QLabel(self.tab_4)
        self.label_56.setStyleSheet("max-height : 800px;\n"
"max-width:1100px;\n"
"margin-top: 10px;\n"
"margin-bottom: 10px;")
        self.label_56.setText("")
        self.label_56.setPixmap(QtGui.QPixmap("../../.designer/Изображения/testImage.jpeg"))
        self.label_56.setScaledContents(True)
        self.label_56.setObjectName("label_56")
        self.gridLayout_6.addWidget(self.label_56, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.horizontalLayout_8.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        self.addItems()
        self.comboBox_1.setCurrentIndex(0)
        self.comboBox_2.setCurrentIndex(1)
        self.comboBox_3.setCurrentIndex(2)
        self.comboBox_4.setCurrentIndex(3)
        self.comboBox_5.setCurrentIndex(4)
        self.comboBox_6.setCurrentIndex(5)
        self.comboBox_7.setCurrentIndex(6)


        handle(self)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.groupBox_2.setTitle(_translate("Dialog", "Уравнения"))
        self.label_28.setText(_translate("Dialog", "F"))
        self.label_30.setText(_translate("Dialog", "F"))
        self.label_34.setText(_translate("Dialog", "F"))
        self.label_37.setText(_translate("Dialog", "F"))
        self.label_39.setText(_translate("Dialog", "F"))
        self.label_61.setText(_translate("Dialog", "F"))
        self.label_71.setText(_translate("Dialog", "F"))

        self.label_46.setText(_translate("Dialog", "(x)="))
        self.label_45.setText(_translate("Dialog", "(x)="))
        self.label_57.setText(_translate("Dialog", "(x)="))
        self.label_58.setText(_translate("Dialog", "(x)="))
        self.label_59.setText(_translate("Dialog", "(x)="))
        self.label_60.setText(_translate("Dialog", "(x)="))
        self.label_70.setText(_translate("Dialog", "(x)="))

        self.comboBox_2.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_2.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_2.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_2.setItemText(6, _translate("Dialog", "7"))
        self.comboBox_2.setItemText(7, _translate("Dialog", "8"))
        self.comboBox_2.setItemText(8, _translate("Dialog", "9"))
        self.comboBox_2.setItemText(9, _translate("Dialog", "10"))
        self.comboBox_2.setItemText(10, _translate("Dialog", "11"))
        self.comboBox_2.setItemText(11, _translate("Dialog", "12"))
        self.comboBox_3.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_3.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_3.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_3.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_3.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_3.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_3.setItemText(6, _translate("Dialog", "7"))
        self.comboBox_3.setItemText(7, _translate("Dialog", "8"))

        self.comboBox_4.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_4.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_4.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_4.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_4.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_4.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_4.setItemText(6, _translate("Dialog", "7"))
        self.comboBox_4.setItemText(7, _translate("Dialog", "8"))
        self.comboBox_5.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_5.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_5.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_5.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_5.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_5.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_5.setItemText(6, _translate("Dialog", "7"))
        self.comboBox_5.setItemText(7, _translate("Dialog", "8"))
        self.comboBox_6.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_6.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_6.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_6.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_6.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_6.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_6.setItemText(6, _translate("Dialog", "7"))
        self.comboBox_6.setItemText(7, _translate("Dialog", "8"))
        self.comboBox_7.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_7.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_7.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_7.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_7.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_7.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_7.setItemText(6, _translate("Dialog", "7"))
        self.comboBox_7.setItemText(7, _translate("Dialog", "8"))
        self.comboBox_1.setItemText(0, _translate("Dialog", "1"))
        self.comboBox_1.setItemText(1, _translate("Dialog", "2"))
        self.comboBox_1.setItemText(2, _translate("Dialog", "3"))
        self.comboBox_1.setItemText(3, _translate("Dialog", "4"))
        self.comboBox_1.setItemText(4, _translate("Dialog", "5"))
        self.comboBox_1.setItemText(5, _translate("Dialog", "6"))
        self.comboBox_1.setItemText(6, _translate("Dialog", "7"))
        self.comboBox_1.setItemText(7, _translate("Dialog", "8"))

        self.expression_lineEdit_1_1.setText(_translate("Dialog", "3"))
        self.expression_lineEdit_2_1.setText(_translate("Dialog", "1"))
        self.expression_lineEdit_3_1.setText(_translate("Dialog", "1"))
        self.expression_lineEdit_4_1.setText(_translate("Dialog", "1"))  
        self.expression_lineEdit_5_1.setText(_translate("Dialog", "1"))
        self.expression_lineEdit_6_1.setText(_translate("Dialog", "1"))
        self.expression_lineEdit_7_1.setText(_translate("Dialog", "1"))
   
        
        self.groupBox_3.setTitle(_translate("Dialog", "Управление"))
        self.label_42.setText(_translate("Dialog", "Статус"))
        self.pushButton.setText(_translate("Dialog", "Вычислить"))
        self.pushButton_2.setText(_translate("Dialog", "График"))
        self.pushButton_3.setText(_translate("Dialog", "Диаграмма"))
        self.groupBox.setTitle(_translate("Dialog", "Начальные уравнения"))

        self.label.setText(_translate("Dialog", "время испарения химически опасных веществ в районе аварии с поверхности земли"))
        self.label_2.setText(_translate("Dialog", "время ликвидации последствий аварии на химически опасном объекте"))
        self.label_3.setText(_translate("Dialog", "количество пораженной техники, ед."))
        self.label_4.setText(_translate("Dialog", "количество пораженных от вторичного облака, чел."))
        self.label_5.setText(_translate("Dialog", "количество растворов для обеззараживания местности"))
        self.label_6.setText(_translate("Dialog", "количество госпитализированных, чел"))
        self.label_7.setText(_translate("Dialog", "количество сил и средств, необходимых для проведения аварийно-спасательных работ"))
        self.label_8.setText(_translate("Dialog", "площадь заражени"))
        self.label_9.setText(_translate("Dialog", "количество пораженных от первичного облака, чел."))
        self.label_10.setText(_translate("Dialog", "эффективность системы оповещения, %."))
        self.label_11.setText(_translate("Dialog", "время подхода первичного и/или вторичного облака к населенным пунктам"))
        
        self.begin_expression_lineEdit_11.setText(_translate("Dialog", "0.5"))
        self.begin_expression_lineEdit_10.setText(_translate("Dialog", "0.67"))
        self.begin_expression_lineEdit_9.setText(_translate("Dialog", "0.5"))
        self.begin_expression_lineEdit_8.setText(_translate("Dialog", "0.78"))
        self.begin_expression_lineEdit_7.setText(_translate("Dialog", "0.29"))
        self.begin_expression_lineEdit_6.setText(_translate("Dialog", "0.5"))
        self.begin_expression_lineEdit_5.setText(_translate("Dialog", "0.8"))
        self.begin_expression_lineEdit_4.setText(_translate("Dialog", "0.5"))
        self.begin_expression_lineEdit_3.setText(_translate("Dialog", "0.6"))
        self.begin_expression_lineEdit_2.setText(_translate("Dialog", "0.9"))
        self.begin_expression_lineEdit_1.setText(_translate("Dialog", "0.8"))

        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Параметры"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Dialog", "Графики"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "Диаграмма"))

    def addItems(self):
        self.comboBox_1.clear()
        self.comboBox_2.clear()
        self.comboBox_3.clear()
        self.comboBox_4.clear()
        self.comboBox_5.clear()
        self.comboBox_6.clear()
        self.comboBox_7.clear()

        for i in range(1, 132):
            self.comboBox_1.addItem(str(i))
            self.comboBox_2.addItem(str(i))
            self.comboBox_3.addItem(str(i))
            self.comboBox_4.addItem(str(i))
            self.comboBox_5.addItem(str(i))
            self.comboBox_6.addItem(str(i))
            self.comboBox_7.addItem(str(i))
