CREATE USER SERVICEDB
  IDENTIFIED BY NzEU39on0sQGbr2CMmVv
  DEFAULT TABLESPACE USERS
  TEMPORARY TABLESPACE TEMP
  QUOTA 100M on USERS;

--Создаем таблицу VEHICLES
CREATE TABLE "SERVICEDB"."VEHICLES" 
   ("ID_VEHICLE" NUMBER(38,0), 
	"ID_OWNER" NUMBER(38,0), 
	"MODEL" VARCHAR2(100), 
	"PLATE" VARCHAR2(100), 
	"ISSUED" VARCHAR2(100), 
	"MILEAGE" NUMBER(38,0), 
	 CONSTRAINT "VEHICLES_PK" PRIMARY KEY ("ID_VEHICLE")
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--Создаем таблицу CUSTOMERS
 CREATE TABLE "SERVICEDB"."CUSTOMERS" 
   ("ID_OWNER" NUMBER(38,0), 
	"NAME" VARCHAR2(100), 
	"ID_VEHICLE" NUMBER(38,0), 
	"PHONE" VARCHAR2(100), 
	"EMAIL" VARCHAR2(100), 
	"DOCUMENT_ID" VARCHAR2(100), 
	 CONSTRAINT "CUSTOMERS_PK" PRIMARY KEY ("ID_OWNER")
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--Добавляем референс на ID_VEHICLE
  ALTER TABLE "SERVICEDB"."CUSTOMERS"
    ADD CONSTRAINT "FK_CUSTOMERS_TO_VEHICLES" FOREIGN KEY ("ID_VEHICLE")
      REFERENCES "SERVICEDB"."VEHICLES" ("ID_VEHICLE") ENABLE;
-------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------
--Создаем таблицу MATERIALS
  CREATE TABLE "SERVICEDB"."MATERIALS" 
   (	"ID_MATERIAL" NUMBER(38,0), 
	"TITLE" VARCHAR2(100), 
	"PRICE" NUMBER(*,0), 
	 CONSTRAINT "MATERIALS_PK" PRIMARY KEY ("ID_MATERIAL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--Создаем таблицу GRADES
  CREATE TABLE "SERVICEDB"."GRADES" 
   ("ID_GRADE" NUMBER(38,0), 
	"DESCRIPTION" VARCHAR2(100), 
	 CONSTRAINT "GRADES_PK" PRIMARY KEY ("ID_GRADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
 --Создаем таблицу STAFF
  CREATE TABLE "SERVICEDB"."STAFF" 
   ("ID_MASTER" NUMBER(38,0), 
	"NAME" VARCHAR2(100), 
	"ID_GRADE" NUMBER(*,0), 
	"QUALIFICATION" VARCHAR2(100),
	"SALARY" NUMBER(*,0),
	 CONSTRAINT "STAFF_PK" PRIMARY KEY ("ID_MASTER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE,
	 CONSTRAINT "FK_STAFF_TO_GRADES" FOREIGN KEY ("ID_GRADE")
	  REFERENCES "SERVICEDB"."GRADES" ("ID_GRADE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
-------------------------------------------------------------------------------------------
-------------------------------------------------------------------------------------------
--Создаем таблицу DIAGNOSTICS
CREATE TABLE "SERVICEDB"."DIAGNOSTICS" 
   ("ID_TICKET" NUMBER(38,0), 
	"JOB" VARCHAR2(100), 
	"DESCRIPTION" VARCHAR2(100), 
	"STATE" VARCHAR2(100), 
	"ID_VEHICLE" NUMBER(*,0), 
	"CONCLUSION" VARCHAR2(100), 
	"ID_MASTER" NUMBER(*,0), 
	"START_DATE" DATE, 
	"DURATION" NUMBER(*,0), 
	 CONSTRAINT "DIAGNOSTICS_PK" PRIMARY KEY ("ID_TICKET")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_DIAGNISTICS_TO_STAFF" FOREIGN KEY ("ID_MASTER")
	  REFERENCES "SERVICEDB"."STAFF" ("ID_MASTER") ENABLE, 
	 CONSTRAINT "FK_DIAGNOSTICS_TO_VEHICLES" FOREIGN KEY ("ID_VEHICLE")
	  REFERENCES "SERVICEDB"."VEHICLES" ("ID_VEHICLE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--Создаем таблицу SERVICE
 CREATE TABLE "SERVICEDB"."SERVICE" 
   ("ID_SERVICE" NUMBER(38,0), 
	"JOB" VARCHAR2(100), 
	"STATE" VARCHAR2(100), 
	"ID_VEHICLE" NUMBER(*,0), 
	"ID_MASTER" NUMBER(*,0), 
	"ID_TICKET" NUMBER(*,0), 
	"START_DATE" DATE, 
	"DURATION" NUMBER(*,0), 
	"ID_MATERIAL" NUMBER(*,0), 
	"CONCLUSION" VARCHAR2(100), 
	 CONSTRAINT "SERVICE_PK" PRIMARY KEY ("ID_SERVICE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_SERVICE_TO_STAFF" FOREIGN KEY ("ID_MASTER")
	  REFERENCES "SERVICEDB"."STAFF" ("ID_MASTER") ENABLE, 
	 CONSTRAINT "FK_SERVICE_TO_VEHICLES" FOREIGN KEY ("ID_VEHICLE")
	  REFERENCES "SERVICEDB"."VEHICLES" ("ID_VEHICLE") ENABLE, 
	 CONSTRAINT "FK_SERVICE_TO_DIAGNOSTICS" FOREIGN KEY ("ID_TICKET")
	  REFERENCES "SERVICEDB"."DIAGNOSTICS" ("ID_TICKET") ENABLE, 
	 CONSTRAINT "FK_SERVICE_TO_MATERIALS" FOREIGN KEY ("ID_MATERIAL")
	  REFERENCES "SERVICEDB"."MATERIALS" ("ID_MATERIAL") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--Создаем таблицу BILLS
CREATE TABLE "SERVICEDB"."BILLS" 
   (	"ID_BILL" NUMBER(38,0), 
	"ID_OWNER" NUMBER(*,0), 
	"ID_TICKET" NUMBER(*,0), 
	"ID_SERVICE" NUMBER(*,0), 
	"AMOUNT" NUMBER(*,0), 
	 CONSTRAINT "BILLS_PK" PRIMARY KEY ("ID_BILL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_BILL_TO_CUSTOMERS" FOREIGN KEY ("ID_OWNER")
	  REFERENCES "SERVICEDB"."CUSTOMERS" ("ID_OWNER") ENABLE, 
	 CONSTRAINT "FK_BILL_TO_DIAGNOSTICS" FOREIGN KEY ("ID_TICKET")
	  REFERENCES "SERVICEDB"."DIAGNOSTICS" ("ID_TICKET") ENABLE, 
	 CONSTRAINT "FK_BILL_TO_SERVICE" FOREIGN KEY ("ID_SERVICE")
	  REFERENCES "SERVICEDB"."SERVICE" ("ID_SERVICE") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;